### ISSUE TITLE
Two children with the same key

### ISSUE THREAD

**Issue by nunottlopes** [marudhupandiyang/react-csv-to-table#5]
```
Warning: Encountered two children with the same key, `210`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

I believe the key for each row shouldn't be `key={`${i}${column}`}` because you can have repeated keys. For example if i = 2 and column = 10, then key = 210, also if i = 21 and column = 0 then key = 210.

Thanks.

**Comment by marudhupandiyang** [comment]
@nunottlopes Thank you. This should be resolved in the latest release
