### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by omerbrandis** [marudhupandiyang/react-csv-to-table#63]
hello , 

{ i'm afraid I'm somewhat new to node,react and such,  }

I've tried installing react-csv-to-table under a standard next.js package/app, this failed with :

46 verbose stack Error: unable to resolve dependency tree
46 verbose stack     at [failPeerConflict] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1381:25)
46 verbose stack     at [loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1347:34)
46 verbose stack     at async [buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:930:11)
46 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:211:7)
46 verbose stack     at async Promise.all (index 1)
46 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
46 verbose stack     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:145:5)
46 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:78:5)
47 verbose cwd /home/omerbrandis/node.js/nextjs1
48 verbose Linux 4.10.0-28-generic
**49 verbose node v18.12.1
50 verbose npm  v8.19.2**
51 error code ERESOLVE
52 error ERESOLVE unable to resolve dependency tree
53 error
**54 error While resolving: nextjs1@0.1.0
54 error Found: react@18.2.0**
54 error node_modules/react
54 error   react@"18.2.0" from the root project
54 error
54 error Could not resolve dependency:
54 error peer react@"^16.8.6" from react-csv-to-table@0.0.4
54 error node_modules/react-csv-to-table
54 error   react-csv-to-table@"*" from the root project
54 error
54 error Fix the upstream dependency conflict, or retry
54 error this command with --force, or --legacy-peer-deps
54 error to accept an incorrect (and potentially broken) dependency resolution.

please advise.
Omer.

**Comment by omerbrandis** [comment]
managed to install with the following command
npm install react-csv-to-table --legacy-peer-deps

**Comment by tomasantunes** [comment]
This is still happening. The solution works but the package needs to be updated.
